dep yml

name: dep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true

        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
          HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}

      - name: Deploy to Railway
        uses: railwayapp/github-action-deploy@main
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_WEBHOOK_ID: ${{ secrets.RAILWAY_WEBHOOK_ID }}
          RAILWAY_WEBHOOK_SECRET: ${{ secrets.RAILWAY_WEBHOOK_SECRET }}
          RAILWAY_REGION: ${{ secrets.RAILWAY_REGION }}

        with:
          railway_api_token: ${{ secrets.RAILWAY_API_TOKEN }}
          railway_project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          railway_webhook_id: ${{ secrets.RAILWAY_WEBHOOK_ID }}
          railway_webhook_secret: ${{ secrets.RAILWAY_WEBHOOK_SECRET }}
          railway_region: ${{ secrets.RAILWAY_REGION }}
